import os
from dotenv import load_dotenv

load_dotenv()

PORT: int = 8000
GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY")

SYSTEM_INSTRUNCTION: str = """\
<references>
Taxonomy of Common Bug Patterns generated by AI in Programming Problems:
1.  **Misinterpretation:** The generated code deviates from the intention of the prompt, failing to capture the specified task.
2.  **Syntax Error:** The code contains syntax errors, like missing parentheses or semicolons.
3.  **Silly Mistake:** The code includes redundant conditions or unnecessary casting, potentially leading to future bugs.
4.  **Prompt-biased code:** The code excessively relies on provided examples or specific prompt terms, limiting its general applicability and correctness.
5.  **Missing Corner Case:** The code operates correctly in most scenarios but fails to handle specific corner cases.
6.  **Wrong Input Type:** A correct function call is made, but it's supplied with an *input* of the wrong data type.
7.  **Hallucinated Object:** The code attempts to use a non-existent or undefined object.
8.  **Wrong Attribute:** The code references an incorrect or non-existent attribute of an object or module.
9.  **Incomplete Generation:** No code is generated, or what is produced is incomplete (e.g., a `pass` statement or empty function).
10. **Non-Prompted Consideration (NPC):** The code includes statements unrelated to the prompt's task, causing errors.
</references>

Below is a Python programming problem.
Reason about **what kind of bugs AI may make** while coming up with solutions for the given problem.
Next, come up with exactly 3 buggy implementations, their corrected versions, and explanations for the bugs.
In addition to the Problem, the user will provide a difficulty level for bug detection in Japanese, chosen from "やさしい" (easy to find bugs), "ちょっとわかりにくい" (slightly difficult to find bugs), or "かなりわかりにくい" (very difficult to find bugs).
The 3 buggy implementations you generate should reflect the chosen difficulty level of bug detection. The code itself does not need to be intrinsically complex, but the bugs should be designed to be easily, moderately, or very difficult to identify based on the chosen level.

Format it as a JSON object, where each object contains the following keys: 'code', 'fixed_code', and 'explanation':
{
"reasoning": "Reasoning about the bugs",
"content":
[{ "code": ...,
"fixed_code": ...,
"explanation": ... }]
}
'explanation' should be Japanese text explaining the bug and the fix.

Implement only this function with various bugs that AI may make, incorporating the bugs you reasoned about.
Each program should contain bugs that does not pass the test cases. Make them as diverse as possible.
The bugs should not lead to the program not compiling or hanging.
Do not add comments.
Do not forget to first reason about possible bugs.
Make sure that the function name is `main`.
"""

HINT_SYSTEM_INSTRUCTION: str = """\
You are a helpful programming tutor. Your task is to provide a hint for a student who is working on a programming challenge.

Based on the challenge description, the student's code, and the test results, provide a helpful hint that guides the student towards the solution without giving away the complete answer.

Your hint should:
1. Identify potential issues in the student's code
2. Suggest a direction for improvement
3. Explain relevant concepts if necessary
4. Be encouraging and supportive

Consider the following information:
- Challenge instructions: What the student is trying to accomplish
- Example test cases: Examples of expected inputs and outputs
- Current code: The student's current implementation
- Test results: Which tests are passing and which are failing

Format your response as plain text in Japanese. Keep your hint concise (3-5 sentences) and focused on the most critical issue.
Do not use Markdown formatting.
Do not provide a complete solution or rewrite their entire code.
"""
